//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oc6.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oc6.Library.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] must be smaller than [{1}].
        /// </summary>
        internal static string CryptoRandomNumberGenerator_MustBeOrdered {
            get {
                return ResourceManager.GetString("CryptoRandomNumberGenerator_MustBeOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address size.
        /// </summary>
        internal static string InvalidAddressSize {
            get {
                return ResourceManager.GetString("InvalidAddressSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mask.
        /// </summary>
        internal static string InvalidMask {
            get {
                return ResourceManager.GetString("InvalidMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.
        /// </summary>
        internal static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List cannot be null.
        /// </summary>
        internal static string ListCannotBeNull {
            get {
                return ResourceManager.GetString("ListCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be positive.
        /// </summary>
        internal static string MustBePositive {
            get {
                return ResourceManager.GetString("MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one parameter must be non-zero.
        /// </summary>
        internal static string NeedsOneNonZeroValue {
            get {
                return ResourceManager.GetString("NeedsOneNonZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments found.
        /// </summary>
        internal static string NoArguments {
            get {
                return ResourceManager.GetString("NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be 0.
        /// </summary>
        internal static string NonZero {
            get {
                return ResourceManager.GetString("NonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number [{0}].
        /// </summary>
        internal static string Parser_InvalidNumber {
            get {
                return ResourceManager.GetString("Parser_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TokenType [{0}].
        /// </summary>
        internal static string Parser_InvalidTokenType {
            get {
                return ResourceManager.GetString("Parser_InvalidTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Variable [{0}].
        /// </summary>
        internal static string Parser_InvalidVariable {
            get {
                return ResourceManager.GetString("Parser_InvalidVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function [{0}] is unknown.
        /// </summary>
        internal static string State_UnknownFunction {
            get {
                return ResourceManager.GetString("State_UnknownFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single character number formats are acceptable.
        /// </summary>
        internal static string Tokenizer_Only_SingleCharacterNumberFormats {
            get {
                return ResourceManager.GetString("Tokenizer_Only_SingleCharacterNumberFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type.
        /// </summary>
        internal static string TokenType_InvalidType {
            get {
                return ResourceManager.GetString("TokenType_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsid must be positive.
        /// </summary>
        internal static string TsidMustBePositive {
            get {
                return ResourceManager.GetString("TsidMustBePositive", resourceCulture);
            }
        }
    }
}
