using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Oc6.Library.Localization
{
    public enum CultureCode
    {
        af_ZA = 1, //Afrikaans - South Africa
        sq_AL = 2, //Albanian - Albania
        ar_DZ = 3, //Arabic - Algeria
        ar_BH = 4, //Arabic - Bahrain
        ar_EG = 5, //Arabic - Egypt
        ar_IQ = 6, //Arabic - Iraq
        ar_JO = 7, //Arabic - Jordan
        ar_KW = 8, //Arabic - Kuwait
        ar_LB = 9, //Arabic - Lebanon
        ar_LY = 10, //Arabic - Libya
        ar_MA = 11, //Arabic - Morocco
        ar_OM = 12, //Arabic - Oman
        ar_QA = 13, //Arabic - Qatar
        ar_SA = 14, //Arabic - Saudi Arabia
        ar_SY = 15, //Arabic - Syria
        ar_TN = 16, //Arabic - Tunisia
        ar_AE = 17, //Arabic - United Arab Emirates
        ar_YE = 18, //Arabic - Yemen
        hy_AM = 19, //Armenian - Armenia
        Cy_az_AZ = 20, //Azeri (Cyrillic) - Azerbaijan
        Lt_az_AZ = 21, //Azeri (Latin) - Azerbaijan
        eu_ES = 22, //Basque - Basque
        be_BY = 23, //Belarusian - Belarus
        bg_BG = 24, //Bulgarian - Bulgaria
        ca_ES = 25, //Catalan - Catalan
        zh_CN = 26, //Chinese - China
        zh_HK = 27, //Chinese - Hong Kong SAR
        zh_MO = 28, //Chinese - Macau SAR
        zh_SG = 29, //Chinese - Singapore
        zh_TW = 30, //Chinese - Taiwan
        zh_CHS = 31, //Chinese (Simplified)
        zh_CHT = 32, //Chinese (Traditional)
        hr_HR = 33, //Croatian - Croatia
        cs_CZ = 34, //Czech - Czech Republic
        da_DK = 35, //Danish - Denmark
        div_MV = 36, //Dhivehi - Maldives
        nl_BE = 37, //Dutch - Belgium
        nl_NL = 38, //Dutch - The Netherlands
        en_AU = 39, //English - Australia
        en_BZ = 40, //English - Belize
        en_CA = 41, //English - Canada
        en_CB = 42, //English - Caribbean
        en_IE = 43, //English - Ireland
        en_JM = 44, //English - Jamaica
        en_NZ = 45, //English - New Zealand
        en_PH = 46, //English - Philippines
        en_ZA = 47, //English - South Africa
        en_TT = 48, //English - Trinidad and Tobago
        en_GB = 49, //English - United Kingdom
        en_US = 50, //English - United States
        en_ZW = 51, //English - Zimbabwe
        et_EE = 52, //Estonian - Estonia
        fo_FO = 53, //Faroese - Faroe Islands
        fa_IR = 54, //Farsi - Iran
        fi_FI = 55, //Finnish - Finland
        fr_BE = 56, //French - Belgium
        fr_CA = 57, //French - Canada
        fr_FR = 58, //French - France
        fr_LU = 59, //French - Luxembourg
        fr_MC = 60, //French - Monaco
        fr_CH = 61, //French - Switzerland
        gl_ES = 62, //Galician - Galician
        ka_GE = 63, //Georgian - Georgia
        de_AT = 64, //German - Austria
        de_DE = 65, //German - Germany
        de_LI = 66, //German - Liechtenstein
        de_LU = 67, //German - Luxembourg
        de_CH = 68, //German - Switzerland
        el_GR = 69, //Greek - Greece
        gu_IN = 70, //Gujarati - India
        he_IL = 71, //Hebrew - Israel
        hi_IN = 72, //Hindi - India
        hu_HU = 73, //Hungarian - Hungary
        is_IS = 74, //Icelandic - Iceland
        id_ID = 75, //Indonesian - Indonesia
        it_IT = 76, //Italian - Italy
        it_CH = 77, //Italian - Switzerland
        ja_JP = 78, //Japanese - Japan
        kn_IN = 79, //Kannada - India
        kk_KZ = 80, //Kazakh - Kazakhstan
        kok_IN = 81, //Konkani - India
        ko_KR = 82, //Korean - Korea
        ky_KZ = 83, //Kyrgyz - Kazakhstan
        lv_LV = 84, //Latvian - Latvia
        lt_LT = 85, //Lithuanian - Lithuania
        mk_MK = 86, //Macedonian (FYROM)
        ms_BN = 87, //Malay - Brunei
        ms_MY = 88, //Malay - Malaysia
        mr_IN = 89, //Marathi - India
        mn_MN = 90, //Mongolian - Mongolia
        nb_NO = 91, //Norwegian (Bokmål) - Norway
        nn_NO = 92, //Norwegian (Nynorsk) - Norway
        pl_PL = 93, //Polish - Poland
        pt_BR = 94, //Portuguese - Brazil
        pt_PT = 95, //Portuguese - Portugal
        pa_IN = 96, //Punjabi - India
        ro_RO = 97, //Romanian - Romania
        ru_RU = 98, //Russian - Russia
        sa_IN = 99, //Sanskrit - India
        Cy_sr_SP = 100, //Serbian (Cyrillic) - Serbia
        Lt_sr_SP = 101, //Serbian (Latin) - Serbia
        sk_SK = 102, //Slovak - Slovakia
        sl_SI = 103, //Slovenian - Slovenia
        es_AR = 104, //Spanish - Argentina
        es_BO = 105, //Spanish - Bolivia
        es_CL = 106, //Spanish - Chile
        es_CO = 107, //Spanish - Colombia
        es_CR = 108, //Spanish - Costa Rica
        es_DO = 109, //Spanish - Dominican Republic
        es_EC = 110, //Spanish - Ecuador
        es_SV = 111, //Spanish - El Salvador
        es_GT = 112, //Spanish - Guatemala
        es_HN = 113, //Spanish - Honduras
        es_MX = 114, //Spanish - Mexico
        es_NI = 115, //Spanish - Nicaragua
        es_PA = 116, //Spanish - Panama
        es_PY = 117, //Spanish - Paraguay
        es_PE = 118, //Spanish - Peru
        es_PR = 119, //Spanish - Puerto Rico
        es_ES = 120, //Spanish - Spain
        es_UY = 121, //Spanish - Uruguay
        es_VE = 122, //Spanish - Venezuela
        sw_KE = 123, //Swahili - Kenya
        sv_FI = 124, //Swedish - Finland
        sv_SE = 125, //Swedish - Sweden
        syr_SY = 126, //Syriac - Syria
        ta_IN = 127, //Tamil - India
        tt_RU = 128, //Tatar - Russia
        te_IN = 129, //Telugu - India
        th_TH = 130, //Thai - Thailand
        tr_TR = 131, //Turkish - Turkey
        uk_UA = 132, //Ukrainian - Ukraine
        ur_PK = 133, //Urdu - Pakistan
        Cy_uz_UZ = 134, //Uzbek (Cyrillic) - Uzbekistan
        Lt_uz_UZ = 135, //Uzbek (Latin) - Uzbekistan
        vi_VN = 136, //Vietnamese - Vietnam
    }
}